# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('currency', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('base_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('band1_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('band2_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('band1_price_range', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('band2_price_range', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('country', models.ManyToManyField(to='shop.Country')),
            ],
            options={
                'verbose_name_plural': 'products',
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_vat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'regions',
                'db_table': 'region',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Region'),
        ),
    ]
