# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_flat_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_tax_free_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
